### ISSUE TITLE
Cannot find pre-configured staging in nexus repo manager 

### ISSUE THREAD

**Issue by leungkinghin** [gradle-nexus/publish-plugin#101]
i followed the document and wrote gradle script as below
```
nexusPublishing {
    repositories {
        sonatype {
            username = System.getenv("MAVEN_USERNAME")
            password = System.getenv("MAVEN_PASSWORD")
        }
    }
}
```
According to the README.md, the nexus URL is pre-configured, so I haven't done further to modify it. Then I run gradle command `PublishToSonatype` to publish my artifact to staging repository without any exceptions. Before publishing it to maven central, I want to make sure if it has been published successfully to staging repo, so I have a loook in nexus repo manager. However I cannot find it successfully. 

If I set artifact library name as -SNAPSHOT, I can find the published artifact in this snapshots repo URL
https://oss.sonatype.org/content/repositories/snapshots/

May I know what the pre-configured URL for staging repository is?

**Comment by szpak** [comment]
Here you are:
https://github.com/gradle-nexus/publish-plugin/blob/f3c24a7b92c5b282fa921cb5f8c966aff6dbf306/src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt#L36-L37

They were published to the new staging repository created by the `initialize*` task. You should be able to check the content using the Nexus UI. This plugin only instruct the built-in `maven-publish` plugin where to upload the artifact. You might want to turn on the `-info` logging or configure it to write more about uploading artifacts (slightly related to #99).

Btw, is should be safe to call `closeSonatypeStagingRepository` to close that repository. Then the content cannot be changed, however, you can still crop that repo from the Nexus UI if you spot any problems.

**Comment by leungkinghin** [comment]
I can find it in Nexus UI now. Thank for you advice :)

**Comment by leungkinghin** [comment]
ok now. I just found i didn't execute those gradle tasks in single invocation.
Anyway thank you for the help 👍🏼
