### ISSUE TITLE
Repositories stay in "state=closed, transitioning=false" on release using 3 different executors

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#102]
I'm facing a similar issue in a Kotlin Multiplatform project, using version 1.1.0 of the plugin. It is built and released simultaneously across 3 different hosts (Linux/macOS/Windows). They all fail late in the process with a similar message, for example:

```
> Task :publishToSonatype
> Task :closeSonatypeStagingRepository

> Task :releaseSonatypeStagingRepository FAILED

FAILURE: Build failed with an exception.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

Use '--warning-mode all' to show the individual deprecation warnings.
* What went wrong:
See docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
Execution failed for task ':releaseSonatypeStagingRepository'.

> Staging repository is not in desired state [released, not_found]: StagingRepository(id=comdoist-1024, state=closed, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to gradle-nexus/publish-plugin/issues with '--info' logs
Execution optimizations have been disabled for 7 invalid unit(s) of work during this build to ensure correctness.
```

When I check Nexus, they show up as closed, and after a few seconds, they are released. The [workflow itself](https://github.com/Doist/doistx-normalize/blob/main/.github/workflows/test-publish.yml#L72) is very basic. Configuration too [[1]](https://github.com/Doist/doistx-normalize/blob/main/buildSrc/src/main/kotlin/publish.gradle.kts#L24-L97) [[2]](https://github.com/Doist/doistx-normalize/blob/main/build.gradle.kts#L91-L105).

Can there be a race condition, or is this misconfiguration on my part?

_Originally posted by @goncalossilva in https://github.com/gradle-nexus/publish-plugin/issues/52#issuecomment-841762196_

**Comment by szpak** [comment]
@goncalossilva It is not expected. I checked your logs and - as it should be - you have different staging repositories created in every build (]here](https://github.com/Doist/doistx-normalize/runs/2593142479#step:9:51) and [here](https://github.com/Doist/doistx-normalize/runs/2593142485#step:9:81)). They should be closed independently. With too short timeout they could be still "closed" , but "transitioning". However, it is not the case here:
> StagingRepository(id=comdoist-1023, state=closed, transitioning=false)

It's strange that they are effectively released after while :thinking: . Does it (being released) occur during the workflow execution or some time later?

To diagnose it I propose to:
1. Add `-i` to the Gradle execution with `./gradlew publishToSonatype ...`
2. Run the workflow.
3. Check when exactly the repositories are marked as released in Nexus UI (in comparison to the given workflow execution).
4. Remove the repositories [section](https://github.com/Doist/doistx-normalize/blob/143b53c29f9db2764baae903658b5586f8461623/buildSrc/src/main/kotlin/publish.gradle.kts#L26-L40) from the publishing block - it should be not needed (I don't know if it can break anything)
5. Run the workflow.

**Comment by goncalossilva** [comment]
> Does it (being released) occur during the workflow execution or some time later?

A little later.

When I noticed that the publish step had failed (took me about 10~30 seconds, I think), I opened Nexus and saw that `comdoist-1022` was still there, in a closed state. When refreshing a few seconds later, it disappeared, without intervention on my part. This was all after the workflows had failed.

> Add -i to the Gradle execution with ./gradlew publishToSonatype ...
> Remove the repositories section from the publishing block - it should be not needed (I don't know if it can break anything)

Done. :+1: 

> Run the workflow.

Is there a way to run the workflow without actually publishing? 1.0.0 already went out yesterday.

---

Thanks for the swift response here!

**Comment by szpak** [comment]
One of the builds [failed to fast](https://github.com/Doist/doistx-normalize/runs/2593142479#step:9:140):
> BUILD FAILED in 1m 30s

Default timeout for transitioning in 1.1.0 should be [10 minutes](https://github.com/gradle-nexus/publish-plugin/blob/master/src/main/kotlin/io/github/gradlenexus/publishplugin/TransitionCheckOptions.kt#L26-L28) per operation. I don't see it modified in your configuration. Maybe there were some error returned from the server. `-i` should help us with it.

> Is there a way to run the workflow without actually publishing?

In general yes - you could use just `closeStagingRepository` instead of `closeAndRelease...`. However, in your case the repo is properly closed (looking at the state) and only the releasing seems to last to long (or rather the task execution gives up too early). Therefore, probably it would be the easiest to wait until you have some material to release 1.0.1 or 1.1.0 :).

Btw, it was your first release with the new releasing machinery - as mentioned in the readme - it might be advised to:
> Please bear in mind that - especially on the initial project publishing to Maven Central - it might be wise to call just publishToSonatype closeSonatypeStagingRepository and manually verify that the artifacts placed in the closed staging repository in Nexus looks ok. After that, the staging repository might be dropped (if needed) or manually released from the Nexus UI.

You might be lucky here, however, looking the published JARs they are quite small (~3,5KB):
https://repo1.maven.org/maven2/com/doist/x/normalize-jvm/1.0.0/

There are no much code in the project, so it might fine, however, I suspect that you already tried to use it in one of your projects (or event better executed some e2e tests :) ) to verify that.

**Comment by goncalossilva** [comment]
> One of the builds failed to fast:

This might be related with the fact that the Windows build uploads a single artifact, while macOS uploads 2, and Linux 3?

> Therefore, probably it would be the easiest to wait until you have some material to release 1.0.1 or 1.1.0 :).

Will do! This might take a while, the library is tiny.

> I suspect that you already tried to use it in one of your projects (or event better executed some e2e tests :) ) to verify that.

Yes, that's accurate. The library is a dependency of an internal project, which has been tested with it. It's a single function, hence the size!

---

It's unclear when we'll release a new version to test out the `-i` switch, so feel free to close the issue for the time being. When we do, I'll circle back. Thanks again!

**Comment by goncalossilva** [comment]
The next release worked well! https://github.com/Doist/doistx-normalize/runs/2615940925?check_suite_focus=true

Ubuntu failed, but that was a configuration mistake. I'd say we're good to close this. :blush:

**Comment by szpak** [comment]
Hmm, your link doesn't work. However, looking at that [one](https://github.com/Doist/doistx-normalize/runs/2616904387?check_suite_focus=true#step:9:896) (windows) or the [other](https://github.com/Doist/doistx-normalize/runs/2616904370?check_suite_focus=true#step:9:1919) (mac) there situation is weird.

After 3 (or more) checks in the release task, that repository should be [switched](https://github.com/gradle-nexus/publish-plugin/runs/2598047449?check_suite_focus=true#step:5:1473) into:
> Current staging repository status: state: not_found, transitioning: false

maybe "state: released, transitioning: true" or "state: released, transitioning: false" (assuming no auto-drop). However, definitely, I would not expect "state: closed, transitioning: false" (at the end of releasing). The release seems to be successful, which suggests that it is "ok"...

The idea that has just sprung to my mind is the fact that your JARs are extremely small. That - assuming delay between checked - might provide previously unexpected results. I will try to reproduce it with some small content or I will just ask the Nexus teams about that case. Their documentation is quite "poor" at the field.

So, let's keep that issue open for now :-).

**Comment by goncalossilva** [comment]
> Hmm, your link doesn't work. However, looking at that one (windows) or the other (mac) there situation is weird.

The build failed because those artifacts had previosly been published! Only the Linux-based ones were missing.

**Comment by szpak** [comment]
That makes sense. The artifacts were reverted to the closed state most likely with some error message available in Nexus UI.

Let me know if you encounter something similar again without a visible error in Nexus.
