### ISSUE TITLE
Publish tasks don't have their publication set

### ISSUE THREAD

**Issue by goncalossilva** [gradle-nexus/publish-plugin#103]
The following code doesn't seem to work with this plugin:

```kotlin
val commonPublications = arrayOf("jvm", "js", "wasm32", "kotlinMultiplatform")
publishing.publications.matching { commonPublications.contains(it.name) }.all {
    tasks.withType<AbstractPublishToMaven>()
        .matching { it.publication == this@all }
        .configureEach { onlyIf { findProperty("publishCommonTargets") == "true" } }
}
```

Debugging, all publishing tasks have a null publication. I am unfamiliar with the internals of the plugin, but does it miss `setPublication` call [around here](https://github.com/gradle-nexus/publish-plugin/blob/master/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L185-L188), e.g.:

```kotlin
publishTask {
    setPublication(publication)
    dependsOn(initializeTask)
    doFirst { logger.info("Uploading to {}", repository.url) }
}
```

?

**Comment by szpak** [comment]
@marcphilipp You seem to be more familiar with the publishing internals. WDYT?

**Comment by vlsi** [comment]
I guess the publishing task in question comes from Gradle itself, and it is Gradle that creates the task.
Then, you have no guarantees when the task is fully configured, so if you install `tasks.withType<...>.matching` filter too early, then you could observe a newly created, non-initialized task.

@goncalossilva , what are you trying to achieve?

**Comment by vlsi** [comment]
I guess the resolution could be:
a) Use task name instead of `task.publication` for filtering: task name is guaranteed to be non-null even at task creation
b) Move filtering into `onlyIf { ..here.. }`. That is defer the filter to task execution
c) Add `afterEvaluate { ....tasks.withType..configureEach {...} }`. That increases the chances of observing non-null `publication`, however, you would have hard time ordering `afterEvaluate` calls coming from different plugins, so the rule of thumb is to avoid `afterEvaluate` at all costs possible

**Comment by goncalossilva** [comment]
> I guess the publishing task in question comes from Gradle itself, and it is Gradle that creates the task.

It does look this way! What I find puzzling was that this code was working before introducing this plugin. :thinking: It broke [here](https://github.com/Doist/doistx-normalize/commit/e6c09c29035b2cc9801f55a19329e70afe3cfd8d).

It's very close to what Kotlin proposes, though it's not applied from within the `kotlin` block: https://kotlinlang.org/docs/mpp-publish-lib.html#avoid-duplicate-publications

Moving it to that block does fix it!

> @goncalossilva , what are you trying to achieve?

This is a multiplatform build, meaning builds happen across 3 hosts (Linux, macOS and Windows). However, some of the targets can be built in any of them (e.g., JVM, JS). The goal is to ensure they are only built when the `publishCommonTargets` property is `true`. Then, it's only set for Linux in CI, and I get automated publications without overlap/conflicts.

> I guess the resolution could be:

These are _excellent_ tips and insights, thansk!
