### ISSUE TITLE
Build Failure when uploading a Snapshot Repository

### ISSUE THREAD

**Issue by christyjacob4** [gradle-nexus/publish-plugin#105]
I'm running the following command to publish my library to a snapshot repository 
```sh
./gradlew --info library:assembleRelease library:publishReleasePublicationToSonatypeRepository
```

But I'm getting this error 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:publishReleasePublicationToSonatypeRepository'.
> Failed to publish publication 'release' to repository 'sonatype'
   > Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/ioappwrite-1026/io/appwrite/sdk-for-android/0.0.1-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request
```

This happens when my publish version has a `-SNAPSHOT` suffix only.
```groovy
publishing {
    publications {
        release(MavenPublication) {
            groupId PUBLISH_GROUP_ID
            artifactId PUBLISH_ARTIFACT_ID
            version '0.0.1-SNAPSHOT'
        }
    }
}
```

When I remove the `-SNAPSHOT` suffix, it works fine. 

This is what the publishing config looks like

```groovy
// Set up Sonatype repository
nexusPublishing {
    repositories {
        sonatype {
            stagingProfileId = sonatypeStagingProfileId
            username = ossrhUsername
            password = ossrhPassword
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
        }
    }
}
```

Any help would be greatly appreciated :smile:

**Comment by marcphilipp** [comment]
By default, the plugin checks the _project_ version (not the publication's version) in order to decide whether to publish to the snapshots or staging repo:

https://github.com/gradle-nexus/publish-plugin/blob/f3df49b4db8ebcdd37846274f0812ed587520e9c/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt#L33-L35

You can customize that via
```kotlin
nexusPublishing {
	useStaging.set(provider {
		// any custom logic goes here
	})
}
```

**Comment by christyjacob4** [comment]
Thank you so much @marcphilipp  ! 
That is probably the reason!

**Comment by christyjacob4** [comment]
@marcphilipp Im not a gradle expert. 

In this snippet 

```groovy
nexusPublishing {
	useStaging.set(provider {
		// any custom logic goes here
	})
}
```

how can I get the details ( version , external properties etc ) of the current module which is being published? 
Could you point me to some docs / resource?  

Thanks again

**Comment by christyjacob4** [comment]
@marcphilipp  I figured it out. 
Thanks for the help :smile:

**Comment by marcphilipp** [comment]
It depends where you're defining the publication. The `useStaging` property is a property of the `NexusPublishinExtension` on the root project so you can't configure it differently for different subprojects.

Assuming you're defining everything in the root project you could access it like this:
```kotlin
nexusPublishing {
	useStaging.set(provider {
		val release: MavenPublication by publishing.publications
		release.version.endsWith("-SNAPSHOT")
	})
}
```

**Comment by USAMAWIZARD** [comment]
@christyjacob4 were you able to solve this

**Comment by vipul-ey** [comment]
Hello @marcphilipp 
Can you please help me with the groovy version of the following snippet:

> ```kotlin
> nexusPublishing {
> 	useStaging.set(provider {
> 		val release: MavenPublication by publishing.publications
> 		release.version.endsWith("-SNAPSHOT")
> 	})
> }
> ```

Here is my version:
```
 useStaging {
        def release = publishing.publications.getByName('release')
        release.version.endsWith('-SNAPSHOT')
    }
```
But seems like it's incorrect.
