### ISSUE TITLE
Task 'publishReleasePublicationToSonatypeRepository' not found in project after update to Gradle 7.0.2 and 'maven-publish'

### ISSUE THREAD

**Issue by phansier** [gradle-nexus/publish-plugin#110]
Just updated the Gradle to 7.0.2 and 'maven' to 'maven-publish'
Received "Task 'publishReleasePublicationToSonatypeRepository' not found"
Are there any plans to support new Gradle?

**Comment by szpak** [comment]
We have smoke tests running with Gradle 7.0 and they seem to be green.

Please put the link to your project or create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by phansier** [comment]
The project is [here](https://github.com/phansier/FlowReactiveNetwork/tree/update)
The commit with the plugin connection is [here](https://github.com/phansier/FlowReactiveNetwork/commit/e9a315522141fe063b6b51be75f89b921019e69a)

**Comment by szpak** [comment]
There could be some problems with releasing Android projects. I don't have experience in Android development, however, there is a [sample project](https://github.com/gradle-nexus/publish-plugin/issues/75#issuecomment-861029942) created by @ViliusSutkus89 which might help you solve your problem.

**Comment by phansier** [comment]
Thank you. I will try to look for decision there and designate the solution here.

**Comment by phansier** [comment]
Found an extra apply of `maven-publish` in library's `build.gradle`
Without it (https://github.com/phansier/FlowReactiveNetwork/commit/9f1dc08776b45d1602ca3b876efeb8ace9729617#diff-b97aa76421eed2ffed0d7e1360290970926a82d973c49784f46858e7eb6b4e75L4) all works as intended.
Sorry to bothering you

**Comment by szpak** [comment]
I didn't know that applying the plugin twice might break publishing. Nevertheless, thanks for sharing your findings! It might be useful for other Android developers
