### ISSUE TITLE
404 405 when publishing release code using self-hosted Maven repository

### ISSUE THREAD

**Issue by XhstormR** [gradle-nexus/publish-plugin#116]
![image](https://user-images.githubusercontent.com/10527522/132157374-d717a4f1-35e3-4291-9b47-9798b1ce5dd4.png)
![image](https://user-images.githubusercontent.com/10527522/132157597-96f90e8a-b549-4233-8978-871c88b96893.png)

I use the following command `gradle publishToSonatype closeAndReleaseSonatypeStagingRepository`

Then I tried adding the following code,  get 405:

```
stagingProfileId.set("fortest")
```

![image](https://user-images.githubusercontent.com/10527522/132157767-0c733c78-bd0d-4c40-9cd9-89ea1dccd2fd.png)

Can anyone tell me how to fix it？

**Comment by XhstormR** [comment]
Snapshot url work fine.

**Comment by XhstormR** [comment]
After testing, I found that our company's maevn does not seem to enable the staging feature. 

I changed the code to the following and successfully uploaded it to the release repo :
![image](https://user-images.githubusercontent.com/10527522/132160564-0f5e85be-cb92-403c-9fbf-f6b6ccb60ec9.png)

But when the stage is explicitly set to false, only snapshotRepositoryUrl is used instead of nexusUrl, so I set snapshotRepositoryUrl to releases url.

It feels weird, but how do I force the use of release nexusUrl。

**Comment by XhstormR** [comment]
https://help.sonatype.com/repomanager2/staging-releases/configuring-the-staging-suite

According to this link, Staging Suite is a feature only available in the pro version, so can the publish-plugin adapt to the open source maven version?

**Comment by ihostage** [comment]
@XhstormR Are you sure that you need this plugin? Looks like you need only [Maven Publish Plugin](https://docs.gradle.org/current/userguide/publishing_maven.html).

**Comment by XhstormR** [comment]
@ihostage I thought the feature of this plugin is a superset of Maven Publish Plugin, which can replace the Maven Publish Plugin that comes with gradle, maybe I thought it wrong.

**Comment by ihostage** [comment]
@XhstormR Yes, this plugin extends the functionality of the Maven Publish Plugin for publishing artifacts to Maven Central or private Nexus Pro. If you use a Nexus OSS, you don't need this plugin 😉

**Comment by XhstormR** [comment]
@ihostage Thank you for the explanation, i got it.
