### ISSUE TITLE
`initializeSonatypeStagingRepository` fails for no obvious reason

### ISSUE THREAD

**Issue by derklaro** [gradle-nexus/publish-plugin#120]
Hey everybody. I'm currently trying to release a library to maven central (for the first using gradle for that instead of maven). I configured my plugin like this:

```groovy
nexusPublishing {
  repositories {
    sonatype {
      nexusUrl.set(uri('https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/'))
      snapshotRepositoryUrl.set(uri('https://s01.oss.sonatype.org/content/repositories/snapshots/'))

      username.set(project.property('ossrhUsername'))
      password.set(project.property('ossrhPassword'))
    }
  }
}
```

Deploying with the url, username and password worked fine with the gradle publish plugin but it created multiple staging repositories so i though it is worth a shot trying this plugin. When i now try to publish for the first time using `./gradlew clean publishToSonatype closeSonatypeStagingRepository` the build fails with:

```
Execution failed for task ':initializeSonatypeStagingRepository'.
> Failed to load staging profiles, server at https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ responded with status code 400, body: {"errors":[{"id":"*","msg":"Cannot find a matching staging profile"}]}
```

I already tried setting the statging profile id, resulting in:

```
Execution failed for task ':initializeSonatypeStagingRepository'.
> Failed to create staging repository, server at https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ responded with status code 400, body: <html>
    <head>
      <title>400 - Bad Request</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  
              
      <link rel="icon" type="image/png" href="https://s01.oss.sonatype.org/favicon.png">
      <!--[if IE]>
      <link rel="SHORTCUT ICON" href="https://s01.oss.sonatype.org/favicon.ico"/>
      <![endif]-->
  
      <link rel="stylesheet" href="https://s01.oss.sonatype.org/static/css/Sonatype-content.css?2.14.20-02" type="text/css" media="screen" title="no title" charset="utf-8">
    </head>
    <body>
      <h1>400 - Bad Request</h1>
      <p>Cannot find a matching staging profile</p>
    </body>
  </html>
 ```
 
 I'm currently not sure what exactly i'm doing wrong... Hopefull someone can help :)

**Comment by derklaro** [comment]
Okay nevermind - changing from the offical documentation staging link `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/` to the uri given in the readme `https://s01.oss.sonatype.org/service/local/` fixed it...

**Comment by Hussienfahmy** [comment]
@derklaro Hello sir.
i tried both of `https://s01.oss.sonatype.org/service/local/` and `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/`
and getting the same errors

**Comment by tomasbjerre** [comment]
In my case I was using the same value (`mavenRepositoryUrl`) as `nexusUrl` in this plugin and as `url` in `repositories`. I changed it to: `mavenRepositoryUrl = "https://oss.sonatype.org/service/local/"` and it now works with this config:

```groovy
nexusPublishing {
	repositories {
		sonatype {
			nexusUrl = uri(mavenRepositoryUrl)
			username = nexusUsername)
			password = nexusPassword)
		}
	}
}

publishing {
        // ... some removed stuff here ...
	repositories {
		maven {
			name = mavenRepositoryName
			credentials(PasswordCredentials)
			url = mavenRepositoryUrl+"staging/deploy/maven2/"
		}
	}
}
```
