### ISSUE TITLE
How to disable checking of `maven-metadata.xml`  on the server during publishToSonatype task?

### ISSUE THREAD

**Issue by tribbloid** [gradle-nexus/publish-plugin#122]
Running ./gradlew publishToSonatype closeSonatypeStagingRepository --info results in the following error:

```
> Task :core:publishMavenPublicationToSonatypeRepository FAILED
Caching disabled for task ':core:publishMavenPublicationToSonatypeRepository' because:
  Build cache is disabled
Task ':core:publishMavenPublicationToSonatypeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Uploading to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1116
Publishing to repository 'sonatype' (https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1116)
Resource missing. [HTTP GET: https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1116/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml]
Uploading maven-metadata.xml to /service/local/staging/deployByRepositoryId/iotryp-1116/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml
:core:publishMavenPublicationToSonatypeRepository (Thread[Execution worker for ':',5,main]) completed. Took 0.438 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
   > Could not PUT 'https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1116/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
15 actionable tasks: 4 executed, 11 up-to-date
Watching 35 directories to track changes

```

It appears that `maven-metadata.xml` cannot be uploaded due to some rule violation. But it doesn't tell exactly what kind of rule. What should I do to fix this problem?

**Comment by szpak** [comment]
It cannot as snapshots shouldn't go to the release repository.

> https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1116/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml

SNAPSHOTs should go a fast track for snapshots. The plugin should detect that situation, it apparently it didn't in this case. I suspect there could be something wrong with the project configuration. Could you share a path to that project?

**Comment by tribbloid** [comment]
Thanks a lot @szpak ! Here is the definition file:

https://github.com/tek/splain/blob/1def631d3805610a86e45dfb887bb67c2134a59e/build.gradle.kts

It is a multi-module project, but I don't think that alone could cause the problem in SNAPSHOT resolving

**Comment by szpak** [comment]
I see you apply version in the publication only (at least in the file you pasted). Please try set it for the Gradle project itself - like here: https://github.com/gradle-nexus/nexus-publish-e2e-multi-project/blob/7a0eccc57ddce63582872f7dc1adef22766d5bb4/build.gradle.kts#L7 and ensure it is not a snapshot (if you want to release it).

AFAIR, the plugin takes it from the root project version and looking at the error, I suspect there mix of snapshot and non-snapshot versions which confuse the release logic.

**Comment by tribbloid** [comment]
thanks a lot! Upgraded:

https://github.com/tek/splain/blob/05b880d527817d884775d9b89be0a40a09d3f0f7/build.gradle.kts

but same problem:

```
> Task :core:publishMavenPublicationToSonatypeRepository FAILED
Caching disabled for task ':core:publishMavenPublicationToSonatypeRepository' because:
  Build cache is disabled
Task ':core:publishMavenPublicationToSonatypeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Uploading to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1119
Publishing to repository 'sonatype' (https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1119)
Resource missing. [HTTP GET: https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1119/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml]
Uploading maven-metadata.xml to /service/local/staging/deployByRepositoryId/iotryp-1119/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml
:core:publishMavenPublicationToSonatypeRepository (Thread[Execution worker for ':',5,main]) completed. Took 0.189 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
   > Could not PUT 'https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1119/io/tryp/splain_2.13.6/1.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request
```

**Comment by szpak** [comment]
I see 1.0.0-SNAPSHOT in your configuration:
https://github.com/tek/splain/blob/ebca0b9d05ca155619f946c237593b520af2475c/buildSrc/src/main/kotlin/Versions.kt#L9

Try to change it to 0.0.1 (or something) and *important* remember to do not call `releaseSonatypeStagingRepository` (just `closeSonatypeStagingRepository`) to be able to drop that repository.

**Comment by tribbloid** [comment]
Thanks a lot! But is it impossible to upload SNAPSHOT just for effect?

Also, this solves 1 problem but bump into another:

```
> Task :core:publishMavenPublicationToSonatypeRepository
Caching disabled for task ':core:publishMavenPublicationToSonatypeRepository' because:
  Build cache is disabled
Task ':core:publishMavenPublicationToSonatypeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Uploading to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1122
Publishing to repository 'sonatype' (https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1122)
Uploading splain_2.13.6-1.0.0-RC1.jar to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.jar
Uploading splain_2.13.6-1.0.0-RC1.pom to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.pom
Uploading splain_2.13.6-1.0.0-RC1.module to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.module
Uploading splain_2.13.6-1.0.0-RC1-javadoc.jar to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1-javadoc.jar
Uploading splain_2.13.6-1.0.0-RC1-sources.jar to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1-sources.jar
Resource missing. [HTTP GET: https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/maven-metadata.xml]
Uploading maven-metadata.xml to /service/local/staging/deployByRepositoryId/iotryp-1122/io/tryp/splain_2.13.6/maven-metadata.xml
:core:publishMavenPublicationToSonatypeRepository (Thread[Execution worker for ':',5,main]) completed. Took 1.686 secs.
:core:publishToSonatype (Thread[Execution worker for ':',5,main]) started.

> Task :core:publishToSonatype
Skipping task ':core:publishToSonatype' as it has no actions.
:core:publishToSonatype (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:closeSonatypeStagingRepository (Thread[Execution worker for ':',5,main]) started.

> Task :closeSonatypeStagingRepository
Caching disabled for task ':closeSonatypeStagingRepository' because:
  Build cache is disabled
Task ':closeSonatypeStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Closing staging repository with id 'iotryp-1122'
Current staging repository status: state: open, transitioning: true
Attempt 1/61 failed with result: StagingRepository(id=iotryp-1122, state=open, transitioning=true)
Current staging repository status: state: open, transitioning: true
Attempt 2/61 failed with result: StagingRepository(id=iotryp-1122, state=open, transitioning=true)
Current staging repository status: state: open, transitioning: true
Attempt 3/61 failed with result: StagingRepository(id=iotryp-1122, state=open, transitioning=true)
Current staging repository status: state: open, transitioning: true
Attempt 4/61 failed with result: StagingRepository(id=iotryp-1122, state=open, transitioning=true)
Current staging repository status: state: open, transitioning: false

> Task :closeSonatypeStagingRepository FAILED
:closeSonatypeStagingRepository (Thread[Execution worker for ':',5,main]) completed. Took 40.516 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':closeSonatypeStagingRepository'.
> Staging repository is not in desired state [closed]: StagingRepository(id=iotryp-1122, state=open, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
```

**Comment by tribbloid** [comment]
Also asked the same question on stackoverflow:

https://stackoverflow.com/questions/69891392/sonatype-nexus-how-to-publish-for-the-first-time-without-maven-metadata-xml

**Comment by szpak** [comment]
> Thanks a lot! But is it impossible to upload SNAPSHOT just for effect?

Definitely it is. However, it should land in the SNAPSHOT repository. This plugin should handle it automatically (and usually it should), but due something specific in your project it is confused. It might be related to https://github.com/gradle-nexus/publish-plugin/issues/75 . As a workaround, you could just temporary disable the plugin (in build.gradle.kts) and publish it as regular publishing:
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:tasks
(gradle-nexus-publish-plugin is needed just to non-snapshot versions)

Regarding:
> Staging repository is not in desired state [closed]: StagingRepository(id=iotryp-1122, state=open, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs

Have you checked the "Nexus web interface"? You should see some error(s) there. Probably you are missing artifact signing - which is required for non-snapshot publishing.

**Comment by tribbloid** [comment]
1. #75 seems to be more relevant to the second problem (I've grepped "SNAPSHOT" in that thread and found nothing)

Since I'm using gradle kts, there should be a way to debug it and show the cause at low level. What kind of repository should I use for SNAPSHOT?

2. Last time I checked the error message is simply:

com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed

So your guess should be correct. Let me figure out how to sign it within the same plugin

**Comment by vlsi** [comment]
> StagingRulesFailedException: One or more rules have failed

I believe it duplicates the existing issue
* https://github.com/gradle-nexus/publish-plugin/issues/55

**Comment by tribbloid** [comment]
I have added the minimal signing:

```
subprojects {

    signing {
        useGpgCmd()
        sign(configurations.archives.get())
    }
```

But nexus still reports the following error:

```
typeId | signature-staging
-- | --
failureMessage | Missing Signature: '/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.jar.asc' does not exist for 'splain_2.13.6-1.0.0-RC1.jar'.
failureMessage | Missing Signature: '/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1-javadoc.jar.asc' does not exist for 'splain_2.13.6-1.0.0-RC1-javadoc.jar'.
failureMessage | Missing Signature: '/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.pom.asc' does not exist for 'splain_2.13.6-1.0.0-RC1.pom'.
failureMessage | Missing Signature: '/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1.module.asc' does not exist for 'splain_2.13.6-1.0.0-RC1.module'.
failureMessage | Missing Signature: '/io/tryp/splain_2.13.6/1.0.0-RC1/splain_2.13.6-1.0.0-RC1-sources.jar.asc' does not exist for 'splain_2.13.6-1.0.0-RC1-sources.jar'.


```

I already have uploaded md5 and sha validation files. What is this asc file and how can I generate it using signing plugin?

**Comment by tribbloid** [comment]
Found the problem: It's probably a new rule for nexus OSS, the signatory has to be openPGP Ascii-armor, `useGpgCmd` is forbidden.

Now the problems becomes how to use the alternative signatory (https://stackoverflow.com/questions/69950064/whats-the-meaning-of-the-error-message-secret-key-ring-doesnt-start-with-sec). Closing this one for now.

**Comment by szpak** [comment]
> Found the problem: It's probably a new rule for nexus OSS, the signatory has to be openPGP Ascii-armor, useGpgCmd is forbidden.

Hmm, I didn't know. Could you link to some information from Sonatype about that change?

Regarding alternative signing, you might be want to use `signing { useInMemoryPgpKeys(...) }`, which was created by @marcphilipp especially for using with CI servers:
https://blog.solidsoft.pl/2020/06/03/simpler-and-safer-artifact-signing-on-ci-server-with-gradle/#simpler-and-safer-artifact-signing

**Comment by tribbloid** [comment]
@szpak yeah that's exactly what I'm using. The secret key is very long and has a special format, a peculiar rule to escape control characters in the ini file may contributes to the error message I encountered
