### ISSUE TITLE
Description should not show a maven coordinate

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle-nexus/publish-plugin#128]
The description is showing a maven coordinate that doesn't exist. And there are cases where there are more artifacts, so showing one has no sense IMO.

I think it should be using the `rootProject` name or the `rootDir` name.

**Comment by marcphilipp** [comment]
You can customize the repository description like this:

```groovy
nexusPublishing {
	repositoryDescription = rootProject.name
}
```

I don't think we'll find one convention that suits all use cases. Seeing the version and coordinates in the name is useful for organizations that publish different artifacts using the same Nexus account.
