### ISSUE TITLE
Closing staging repository fails

### ISSUE THREAD

**Issue by nrbrook** [gradle-nexus/publish-plugin#141]
I'm using Gradle Nexus Publish Plugin 1.1.0 and it fails when closing the staging repository. It looks like it only tries once before failing. Also it then continues to run the release task which fails because it is not closed.

```
...
:closeSonatypeStagingRepository (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :closeSonatypeStagingRepository
Caching disabled for task ':closeSonatypeStagingRepository' because:
  Build cache is disabled
Task ':closeSonatypeStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Closing staging repository with id 'ionrbtechrxandroidble-1011'
Current staging repository status: state: open, transitioning: true
Attempt 1/61 failed with result: StagingRepository(id=ionrbtechrxandroidble-1011, state=open, transitioning=true)
Current staging repository status: state: open, transitioning: false

> Task :closeSonatypeStagingRepository FAILED
:closeSonatypeStagingRepository (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 10.797 secs.
:releaseSonatypeStagingRepository (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :releaseSonatypeStagingRepository FAILED
Caching disabled for task ':releaseSonatypeStagingRepository' because:
  Build cache is disabled
Task ':releaseSonatypeStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Releasing staging repository with id 'ionrbtechrxandroidble-1011'
:releaseSonatypeStagingRepository (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.616 secs.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':closeSonatypeStagingRepository'.
> Staging repository is not in desired state [closed]: StagingRepository(id=ionrbtechrxandroidble-1011, state=open, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':releaseSonatypeStagingRepository'.
> Failed to release staging repository, server at https://s01.oss.sonatype.org/service/local/ responded with status code 500, body: {"errors":[{"id":"*","msg":"Unhandled: Repository: ionrbtechrxandroidble-1011 has invalid state: open"}]}

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 34s
63 actionable tasks: 15 executed, 48 up-to-date
Watched directory hierarchies: [/Users/nick/Documents/Repos/AirTurnSDK/RxAndroidBle]
```

**Comment by szpak** [comment]
How do you call it? Do you use `--parallel` or `--continue`?

**Comment by nrbrook** [comment]
`./gradlew --info :rxandroidble:publishToSonatype :mockrxandroidble:publishToSonatype closeAndReleaseSonatypeStagingRepository`

**Comment by szpak** [comment]
I'm not sure why the close task fails after `1/61`. Do you have that project (and the execution) publicly available?

Regarding, the second failure, do you, by any chance, have `finalizedBy` used for those two tasks?

**Comment by szpak** [comment]
Update. I was mislead by `StagingRepository(id=ionrbtechrxandroidble-1011, state=open, transitioning=true)`. However, in the error message there is: 
> Execution failed for task ':closeSonatypeStagingRepository'.
> Staging repository is not in desired state [closed]: StagingRepository(id=ionrbtechrxandroidble-1011, state=open, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs

`transitioning=false` means the server refused to close the repository. Most likely due to validation check (e.g. missing checksums)

**Comment by nrbrook** [comment]
> I'm not sure why the close task fails after `1/61`. Do you have that project (and the execution) publicly available?

https://github.com/NRB-Tech/RxAndroidBle/runs/5696041462?check_suite_focus=true

> Regarding, the second failure, do you, by any chance, have `finalizedBy` used for those two tasks?

No I don't think so

**Comment by szpak** [comment]
> It could have been because I was attempting to publish the same version - would this cause it

If that version has been already published Nexus should refuse the second operation. Have you checked in the Nexus UI? There should be a detailed message.

**Comment by nrbrook** [comment]
When doing this manually, closing works fine, then releasing shows an error, but I refreshed and the staging repository disappeared. I can't see any other logs or records of the failure. I am publishing to maven central. After this failure I was able to publish successfully from my local machine with a new version number. I'm unsure if this failure was just because of the version number, because of some difference when running with GitHub actions, or if it only fails sometimes.

**Comment by szpak** [comment]
> When doing this manually, closing works fine, then releasing shows an error, but I refreshed and the staging repository disappeared. I can't see any other logs or records of the failure, where should I be looking? I am publishing to maven central.

Having the close operation failed should leave a staging repository in an open state (and transitioning false) which should be available in the Nexus UI. The repository could be purged after some time, but usually it is counted in months. When releasing fails, it should be auto-drop after success, but AFAIR it should stay after failure.

I propose, to try to reproduce a problem with closing from CI (even without the release step to do not generate junk versions in Maven Central). After a (closing) failure, there should be error mentioned in the staging repository. However, as you mentioned, it could be caused by a duplicated version.

**Comment by nrbrook** [comment]
Ok thanks, I will try to run close from GitHub.
Maybe same version errors are different? Because you can have multiple staging repositories of the same version. Closing seemed to work fine even though the version was already released. The error occurred when releasing I think. I'll play around a bit more though.

**Comment by nrbrook** [comment]
Close only from github worked now, even with an already released version. I'm unsure why it wasn't working before. I think I'll close this issue now and open a new issue if I have problems with the next release.
