### ISSUE TITLE
`releaseSonatypeStagingRepository` fails even if release was successful

### ISSUE THREAD

**Issue by codecholeric** [gradle-nexus/publish-plugin#146]
When I tried to release last time the release build failed with this exception:

```
Execution failed for task ':releaseSonatypeStagingRepository'.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> Staging repository is not in desired state [released, not_found]: StagingRepository(id=comtngtech-1552, state=closed, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs
```

However, going to the Nexus web interface I saw that the release actually went through successfully. Unfortunately, I can't provide any `--info` logs, since the release is through now and I can't repeat it. 

Could this have been a timeout problem? But AFAIS the default should [pull 10 mins](https://github.com/gradle-nexus/publish-plugin#retries-for-state-transitions) for state changes, right? And the whole build had only run 6 mins at this point :thinking:

**Comment by vlsi** [comment]
It looks like it is worth adding closed to the list of statuses in https://github.com/gradle-nexus/publish-plugin/blob/0aea95597e2eeaf9275a286254894bad29b3d1e1/src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt#L33-L34

**Comment by szpak** [comment]
Thanks for the report. There could be some changes in Nexus, but AFAIR the API call to trigger the release finished not earlier than having the repository in "inTransitioning=true". Here, it is both closed and not transitioning. Assuming there were no other issues (the repo was in the end transited successfully) it is quite strange.

I would be reluctant to just add that status before easing the "--info" log (possibly in the another case, we can wait for it) and even better to find in the Nexus API documentation (maybe one has been created in the meantime) confirming that is possible.

**Comment by vlsi** [comment]
@szpak , `transitioning=false ` is indeed strange, however, can it be something like "nexus received command to transition the repository, however, the command hasn't yet started"?
In other words, what if it hasn't had a chance to even start the transition?

**Comment by vlsi** [comment]
I've filed https://issues.sonatype.org/browse/NEXUS-34163 to ask for a recommendation regarding the wait for the promotion to complete.

**Comment by szpak** [comment]
I believe that - in the past - the REST endpoint would wait until the transitioning is started, but I might be wrong or something could have changed. Thanks for creating an issue!

Btw, can you add user `szpak` to that issue or make it public? I see:

> You can't view this issue
> It may have been deleted or you don't have permission to view it. 

Alternatively, please paste here their answer.

**Comment by vlsi** [comment]
Oh, I just realized I might have used the wrong JIRA instance. I can't add people to the issue, sorry :-/
I wonder if I should have used https://issues.sonatype.org/projects/OSSRH instead.
Let us wait a bit for the response.

Here's what I put to the issue description:

>It looks like https://support.sonatype.com/hc/en-us/articles/213465448-Automatically-dropping-old-staging-repositories is the only documentation available for /service/local/staging/bulk/promote.
>Unfortunately, it does not clarify the way to wait till the promotion finishes.

>https://github.com/gradle-nexus/publish-plugin uses this API to release repositories (autoDropAfterRelease:true)

>The code calls {{/service/local/staging/bulk/promote}}, and then waits for some time and checks the repository status via {{staging/repository/<stagingRepoId>}} requests.

>Based on the past experience, it was expected to observe the following outcomes:
>a) any state, transitioning=true. It looks like the repository is transitioning, so wait a bit.
>b) released. Ok, the repository has been released, end of wait.
>c) 404 NOT_FOUND. It means the repository has already been dropped, end of wait.

>However, recently there was a case when Nexus returned {{id=comtngtech-1552, state=closed, transitioning=false}} during promotion.
>In fact, the repository has been successfully promoted, however, it was unexpected to observe transitioning=false state.

>Unfortunately, there's no much logs for that case, and
https://github.com/gradle-nexus/publish-plugin/issues/146 is the only information available.

>**Question**: Could you please clarify what is the recommended way to wait for promotion to complete? Is state=closed & transitioning=false a valid outcome after a successful staging/bulk/promote request?

**Comment by vlsi** [comment]
So far they thanked me for filing the issue and responded they no longer maintain v2 APIs, and they suggest users to migrate to Repository v3 which has better APIs for staging: https://help.sonatype.com/repomanager3/nexus-repository-administration/staging

I'm not sure it applies to OSSRH since oss.sonatype.org still uses Nexus 2.15.1-02, so I asked for a clarification.

**Comment by codecholeric** [comment]
Did they ever get back to you? Otherwise, maybe really file the issue at https://issues.sonatype.org/projects/OSSRH? Because there they can hardly say that you should upgrade to v3, right? :wink:

**Comment by vlsi** [comment]
Their answer indeed was "we recommend all users migrate to Repository v3", and they ignored my request to reopen the issue 🤷‍♂️ 

Let me file a new one as "clarify API or upgrade Central to v3" :)

**Comment by vlsi** [comment]
I've filed https://issues.sonatype.org/browse/OSSRH-84806

**Comment by codecholeric** [comment]
Thanks a lot for following up on it, really appreciated :slightly_smiling_face:

**Comment by vlsi** [comment]
@codecholeric , could you please clarify if you observed the issue with `oss.sonatype.org` or with `s01.oss.sonatype.org`?

**Comment by vlsi** [comment]
@codecholeric , up? Could you please clarify if you observed the issue with oss.sonatype.org or with s01.oss.sonatype.org?

**Comment by szpak** [comment]
I'm going to close this issue due to inactivity. @codecholeric, if you're still facing the problem please comment here.
