### ISSUE TITLE
Migration to plugin causes Gradle Plugin Portal coordinates to change

### ISSUE THREAD

**Issue by andrewparmet** [gradle-nexus/publish-plugin#151]
I've migrated to this plugin from `gradle-nexus-staging-plugin` and my Gradle Plugin Portal coordinates suddenly changed - from `com.parmet.buf` to `gradle.plugin.com.parmet`. I'm thinking it must have been this plugin because I didn't change my Gradle plugin publishing config, but I don't see where this plugin would affect that. Is there something I'm missing?

Here's the migration: https://github.com/andrewparmet/buf-gradle-plugin/compare/1ef3a55ccaa5e326410dc4a6a2aea1b442bc8605...5cc2c1ddd4dd4e93cb23581be076759d99e1adbd

Thanks!

**Comment by vlsi** [comment]
I guess `com.parmet.buf` to `gradle.plugin.com.parmet` is not related to `gradle-nexus/publish-plugin`.

**Comment by andrewparmet** [comment]
Ah, it's documented here: https://plugins.gradle.org/docs/publish-plugin-legacy "Group ID can't start with gradle.plugin".

I removed the maven-publish plugin as part of this migration.
