### ISSUE TITLE
Report `state=closed, transitioning=false` as "artifact already published"

### ISSUE THREAD

**Issue by nedtwigg** [gradle-nexus/publish-plugin#155]
I just triggered a deployment which failed

- https://github.com/diffplug/spotless/actions/runs/4097459157/jobs/7065848299
- > Staging repository is not in desired state [released, not_found]: StagingRepository(id=comdiffplug-1120, state=closed, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation.

Googling around led me to

- https://github.com/gradle-nexus/publish-plugin/issues/102

Which had the very helpful info

> The build failed because those artifacts had previosly been published! Only the Linux-based ones were missing.

And in fact that turned out to be my problem too! I kicked off deployment on a stale branch 👎 

It would be helpful if the error message for `state=closed, transitioning=false` had a hint like "This probably means you have already published artifacts with these names and versions."

I'd be happy to submit a PR for this, but I'm a bit afraid the project has died, because #152 is important and easy to fix and is remaining unfixed. Thanks very much for making this, you've got no obligation to keep maintaining it! But if you do get around to fixing #152, I promise to come back and submit a little PR for better error messages if you'd like it :)

**Comment by szpak** [comment]
In fact, in the error message there is:
> It is unexpected. Please check Nexus logs using its web interface - it can be caused by validation rules violation.

Did the error reported in Nexus explain why it happened in your case?

In general, there could be some other cases to fail on the Nexus/Sonatype validation, but I agree the duplicated versions/artifacts are probably the most common, so the error message could be improved.

**Comment by nedtwigg** [comment]
I couldn't figure out how to find the logs, but definitely the problem was the duplicate version, once I ran the job from the correct branch it worked. The setup had worked unchanged for a long time until this.

**Comment by szpak** [comment]
Next time, after the aforementioned failure, go to https://oss.sonatype.org/ , log inm find there your staging repository (by name) and check its status (in the lower panel). There are several validation checks in Sonatype release policy and one of them is most likely failed, with a clear error message.
I believe, there was even a proposal to try get that error message from Nexus (however, we don't use that API yet).
