### ISSUE TITLE
Add more committers/releasers

### ISSUE THREAD

**Issue by vlsi** [gradle-nexus/publish-plugin#156]
It looks like the current maintainers have little time for review and maintenance.

Here's my PR waiting for 7 months: https://github.com/gradle-nexus/publish-plugin/pull/145

I suggest adding someone to the team.

For instance, what do you think of addig me to the team?

**Comment by sschuberth** [comment]
Yes, moving development forward by adding experienced committers like @vlsi sounds like a good plan.

**Comment by szpak** [comment]
We've added @TWiStErRob to the team a few months ago after his broad contribution to the project. @sschuberth if you would like to contribute to the project (code, documentation, conference evangelism, ...) please do so.

As the aforementioned PR #145 has been merged (as #201), I'm closing this issue for now.

**Comment by TWiStErRob** [comment]
For anyone finding this in the future: contributions are not all code-based. Answering an issue, reviewing existing PRs are both extremely helpful and move things along. (In the past, I used to just support Glide for Android, while the lead maintainer was doing the code/PR part.)

If you are able, feel free to review any PRs to help your fellow community members.

Also keep the PRs focused and small (not just here, anywhere), as the bigger the PR the more effort is to review it and reason about its validity, leading to longer lead times.
