### ISSUE TITLE
findSonatypeStagingRepository task does not exist?

### ISSUE THREAD

**Issue by bitspittle** [gradle-nexus/publish-plugin#204]
The README recommends using a task called `findSonatypeStagingRepository` but I don't seem to have it. I'm using the latest release (1.2.0). 

Is the README stale and/or talking about a feature that hasn't yet been released?

**Comment by szpak** [comment]
Thanks for the report. We should switch to release after (almost every) merge to master or keep the changes (at least in README) in a `devel` branch. [That feature](https://github.com/gradle-nexus/publish-plugin/pull/201) is in the main branch and will be available in 1.3.0 (to be released "soon").

**Comment by szpak** [comment]
Btw, I wonder, what is your usecase for that feature? Is it a Apache project? Or anything else?

**Comment by szpak** [comment]
@bitspittle I've just released [1.3.0](https://github.com/gradle-nexus/publish-plugin/releases/tag/v1.3.0) - especially for you :-). Please give it a try.

**Comment by bitspittle** [comment]
Wow, thanks for the quick replies! That was responsive.

> I've just released [1.3.0](https://github.com/gradle-nexus/publish-plugin/releases/tag/v1.3.0) - especially for you :-). Please give it a try.

Well, I should have procrastinated more today :smile: 

> Btw, I wonder, what is your usecase for that feature? Is it a Apache project? Or anything else?

Honestly, today was a domino of failures with Sonatype and I was just looking for a way out.

Background: [My project](https://github.com/varabyte/truthish) is a Kotlin multiplatform library, and I use a CI to build it. I actually use two runners, a Linux runner and a Mac runner (the first for creating Linux, Windows, and Android artifacts; the latter for Mac and iOS).

In the past, I would use the Sonatype web UI, but somewhat recently, there have now been two days where I wanted to release artifacts, only to be met with a blank page that showed a timeout popup each time I tried to refresh the staging properties. Today, of course, and I think a few weeks ago?

Last time it happened, I learned about this plugin, and thanks to `closeAndReleaseSonatypeStagingRepository` I was able to get around the unresponsive UI.

Today, however, `closeAndReleaseSonatypeStagingRepository` didn't work. Then, I went to the web UI, which was, as mentioned above, timing out.

I was getting the error that looks something like "sonatype staging server could not be found." I know from my previous experience, this was caused by not using `closeAndReleaseSonatypeStagingRepository` in the same invocation as the publish task, but I was confused since this time I *was* doing that. (When I dug into the logs, I was getting a 405 Error: Method Not Found, when trying to deploy my artifacts to Sonatype; was there some sort of migration happening on the backend today?)

So I came to the README to double check if there was anything that I missed, at which point I saw the updated information about `findSonatypeStagingRepository`. However, when I checked latest releases, it was set to 1.2.0 which I already had, but I didn't have that task.

And that's what ultimately brought me here  to file this issue :)

At some point later in the day, the Sonatype web UI started responding again, so I went ahead and released my staged artifacts that way.

In the future though, I think having the CI stage the artifacts and then me, from my desktop, firing the event that releases them, will be pretty convenient. 

Honestly, I'm a little nervous about releasing artifacts directly from a CI, because I worry about the case where it releases half of them only for the CI to get shutdown halfway through (it has flaked on me before). Having only half of my artifacts getting released to `mavenCentral` sounds like a pain to deal with -- I'd probably have to edit my CI workflow ASAP to create a new version for publishing the remaining half. But in contrast, if *staging* breaks halfway through, who cares? I can just restage a new batch.

 I should be releasing artifacts for [a different project](https://github.com/varabyte/kotter) in the near future, so I'll try 1.3.0 out then. Thanks for your hard work!

**Comment by szpak** [comment]
Thanks for your elaboration!

> Honestly, I'm a little nervous about releasing artifacts directly from a CI, because I worry about the case where it releases half of them only for the CI to get shutdown halfway through (it has flaked on me before).

I had the same feelings and to verify the pipeline, I started with just closing the staging repository from CI, manually verify its content via UI and releasing it (the staging repository) via UI.

Probably starting with the CI for a simpler project (if you already have one) could be easier.

**Comment by itsdebs** [comment]
@szpak I have the same multi module structure in my library, and I am using the following command, but somehow `findSonatypeStatgingRepository` is getting skipped, and I have to manually go back to sonatype web ui to close and release the repository.
`./gradlew publishToSonatype -p mymodule -Prelease && ./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository && ./gradlew findSonatypeStagingRepository releaseSonatypeStagingRepository`
