### ISSUE TITLE
Gradle 8.2 deprecated conventions and added nagging

### ISSUE THREAD

**Issue by TWiStErRob** [gradle-nexus/publish-plugin#226]
From this plugin every user will get this:
```
> Configure project :
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin.addMavenRepositories(NexusPublishPlugin.kt:273)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin.access$addMavenRepositories(NexusPublishPlugin.kt:40)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin$configurePublishingForAllProjects$1$1$1.execute(NexusPublishPlugin.kt:157)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin$configurePublishingForAllProjects$1$1$1.execute(NexusPublishPlugin.kt:40)
```

There isn't much to do to fix this, only we need to compile the project with Gradle 8.2 as suggested here:
https://github.com/gradle/gradle/issues/25206

However, using Gradle 8.2 is not trivial, it requires these steps (and shows how useful it is to merge Renovate PRs soon-ish 😉):

- [x] Merge https://github.com/gradle-nexus/publish-plugin/pull/194 (trivial)
- [x] Merge https://github.com/gradle-nexus/publish-plugin/pull/210 (quick review)  
      which supersedes https://github.com/gradle-nexus/publish-plugin/pull/197
- [ ] Merge https://github.com/gradle-nexus/publish-plugin/pull/225  
      which supersedes https://github.com/gradle-nexus/publish-plugin/pull/195
- [ ] Renovate will rebrand this PR to 8.2 as soon as it's released:  
      https://github.com/gradle-nexus/publish-plugin/pull/214 (trivial)
- [ ] Release 1.3.1 (if there are no other breaking changes)

@szpak Timeline to do this is a few weeks until Gradle 8.2 becomes stable.

**Comment by szpak** [comment]
Thanks @TWiStErRob . I will work on that "soon", after #222 is merged. Btw, what other (potentially non-backward incompatible) changes would you see before 2.0.0?

**Comment by maczikasz** [comment]
FYI the PR #222 will actually fix that nagging for 8.2

**Comment by TWiStErRob** [comment]
Cool, good to hear @maczikasz. Note: there were 2 or 3 `the` calls. That means this is not urgent, but still would be nice to unblock contributions behind an epic PR :)

**Comment by TWiStErRob** [comment]
@szpak none of what I listed is backwards incompatible IMO. I don't think there's too much need to be afraid of backwards compatibility. Just provide a good migration guide, and then it takes 3 minutes to do a breaking upgrade. 😉 e.g. Stutter's 0.7 is a good example, it's totally changed, yet nothing really changed so it was easy.

**Comment by TWiStErRob** [comment]
Closing this as fixed by #222 (see [diff](https://github.com/gradle-nexus/publish-plugin/pull/222/files#diff-b2a3da37a258c425816cd39eae24832449cdbb041fc3d1038219c090a2f0f71d)), because that PR changed the `.the<>` calls to extension access. (This was the second option recommended by https://github.com/gradle/gradle/issues/25206)

@szpak add milestone?

**Comment by TWiStErRob** [comment]
@szpak Can you please release this? Gradle 8.2 is released stable. e.g. Mockito is affected.

**Comment by szpak** [comment]
Can you give [2.0.0-rc-1](https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin) as try?

**Comment by TWiStErRob** [comment]
Oh, 🤦‍♂️ I forgot that was released. Please do mark it as pre-release so it shows in Releases view on GitHub.

**Comment by szpak** [comment]
[Done](https://github.com/gradle-nexus/publish-plugin/releases/tag/v2.0.0-rc-1). In fact the tag was, but I needed to "generate" the changelog and create a pre-release.
