### ISSUE TITLE
Kotlin DSL friendly overall tasks

### ISSUE THREAD

**Issue by Vampire** [gradle-nexus/publish-plugin#236]
You have the `closeAndReleaseStagingRepository` task (which should probably better be called `closeAndReleaseStagingRepositories`).
This task is always registered no matter which repositories are configured.
This is good, as then we also get type-safe accessors for the Kotlin DSL for it.
And as typically only Maven Central is configured, this is also a perfect replacement for the `closeAndReleaseSonatypeStagingRepository` task that does not get accessors generated.

The problem is, that I don't want to do close and release coupled.
I do the closing when doing also other publishing tasks like creating the GitHub publication.
Only after also all other tasks were successful, I want to release the repository.

So I would welcome `closeStagingRepositor(y/ies)` and `releaseStagingRepositor(y/ies)` to conveniently wire them using Kotlin DSL.

**Comment by sschuberth** [comment]
Looks like this issue is actually not so much about Kotlin DSL, but somewhat duplicates https://github.com/gradle-nexus/publish-plugin/issues/215 and https://github.com/gradle-nexus/publish-plugin/issues/134 (and is quite the opposite of https://github.com/gradle-nexus/publish-plugin/issues/77).

**Comment by Vampire** [comment]
Not really @sschuberth.
This is about adding summary tasks for only closing and only releasing like there is one for closing and releasing together.
This is not too tightly related to Kotlin DSL, but makes the usage better in Kotlin DSL as described above.

#215 is about the standalone closing and releasing somehow having some problem
#134 is about the possibility to upload multiple things in multiple Gradle runs and then do a close and release for them together in a separate run
#77 is not at all opposite to this request, it just requests some combination tasks that that combine publishing and closing which is totally independent of this request

**Comment by sschuberth** [comment]
> Well, while we are at it, I implemented it in #285 :-D

[Good luck](https://github.com/gradle-nexus/publish-plugin/issues/156) with getting it merged (honestly, no sarcasm here).
