### ISSUE TITLE
Publish different library types to same repository

### ISSUE THREAD

**Issue by blackarrow13** [gradle-nexus/publish-plugin#273]
I develop a library which has a slightly different code for apps in Google Play and in Huawei AppGallery (I use two different local modules in in gradle dependencies).  I used to do something like this in a script:
```
./gradlew -Pplatform=huawei :mylib:publishAllPublicationsToStageRepository
./gradlew -Pplatform=google :mylib:publishAllPublicationsToStageRepository
./gradlew closeSonatypeStagingRepository
```
and both artifacts were added to the same repository, just as I wanted. "Close" step was failing with
```
Execution failed for task ':closeSonatypeStagingRepository'.
> Failed to calculate the value of task ':closeSonatypeStagingRepository' property 'stagingRepositoryId'.
   > No staging repository with name sonatype created
```
but I could close and release it manually.

I wanted to fix the need for a manual step and tried the following (with version 1.3.0 of this plugin)
```
./gradlew -Pplatform=huawei :mylib:publishToSonatype
./gradlew -Pplatform=google :mylib:publishToSonatype
./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository
```
Now I have my artifacts in two separate repositories because repository is created in publishToSonatype.
Is there a way to confgure my project such that both artifacts are in the same repository, it is closed and released automatically?

**Comment by TWiStErRob** [comment]
I'll let @szpak advise on the Sonatype part, but I can think of a workaround.

I'm assuming that by "library" you mean `com.android.library` from AGP. Which means you have fully featured flavour/variant APIs to create this split of "slightly different code". If you migrate your `-Pplatform=` solution to variants, that means you could have two tasks, one for each artifact:
```shell
./gradlew :mylib:publishHuaweiToSonatype :mylib:publishGoogleToSonatype
```
Since these would be running in the same build, I think Sonatype would put them in the same staging repo.

Related AGP APIs:
 * https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/LibraryPublishing
 * https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/PublishingOptions

---

As a side-effect this would eliminate the need for conditional code in build.gradle via `huaweiImplementation` and `googleImplementation` dependency configurations. And it might simplify your CI too as you can run different tasks, rather than juggle properties.

**Comment by blackarrow13** [comment]
Thanks a lot, I will try this approach!

> I'm assuming that by "library" you mean com.android.library from AGP
Yes

If I migrate to variants,  do I need to define the tasks publishHuaweiToSonatype, publishGoogleToSonatype myself or they are automatically available (publish{$variant}toSonatype)?
If I need to define them myself, could you please show me how would they look, roughly?
If both tasks depend on publishToSonatype, gradle would only run it once and publish only one variant, if I understand it right

**Comment by TWiStErRob** [comment]
> If I migrate to variants, do I need to define the tasks publishHuaweiToSonatype, publishGoogleToSonatype myself or they are automatically available (publish{$variant}toSonatype)?

Half automatic, see the LibraryPublishing for an example. Each publication will have its `publish${publicationName}To${repository}` tasks.

> If I need to define them myself, could you please show me how would they look, roughly?

Same, see LibraryPublishing, that should give you an idea, if not, I recommend to search GitHub there must be examples, e.g. in the official https://github.com/android/gradle-recipes

> If both tasks depend on publishToSonatype, gradle would only run it once and publish only one variant, if I understand it right

As far as I know `publishTo${repository}` is a shorthand for `publishMainToSonatype` or in case of Android: `publishReleaseToSonatype`, but I didn't look if this is true.

---

@szpak is there a way to say "gradlew publishXYZToSonatype -PexactlyToThisRepo=12345`?

**Comment by blackarrow13** [comment]
I achieved what I needed by following your suggestion and refactoring my project. Now I have three modules - libcore which contains common code, libgoogle with code used only in google apps and libhuawei for huawei apps only. I execute this in a single gradle command:
`./gradlew :libcore:publishToSonatype :libgoogle:publishToSonatype :libhuawei:publishToSonatype`
and all my artifacts end up in the same repository as I wanted.
then I call
`./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository`

The library users need to add two dependencies but that is acceptable for me. It may even be desired for projects releasing the same app to both stores.

Thanks a lot for your help! From my point this question can be closed.

**Comment by szpak** [comment]
@blackarrow13 I'm glad you - with support from @TWiStErRob - were able to solved your problem.

Anyhow, you can is interesting and also looking at #275, might be useful to have it better supported.

`stagingRepositoryId` can be passed as a parameter to the close and release tasks. It is done to be able to separate publishing the real artifacts to a staging repository from the process of their closing (could be a separate step in pipeline) and releasing (for example after manual testing). It's possible as they only "mustRunAfter" the publishing tasks:
https://github.com/gradle-nexus/publish-plugin/blob/ec9b015298c54309728fa03af3b913f92aa304f5/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L318-L323

To avoid using heuristics when more than one stating repository is open (or in general in a given state), a separate staging repository is created before publishing and there is a "dependsOn" relation:
https://github.com/gradle-nexus/publish-plugin/blob/ec9b015298c54309728fa03af3b913f92aa304f5/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L306-L307

So, the quick answer is: it is currently not possible to achieve:
> gradlew publishXYZToSonatype -PexactlyToThisRepo=12345`

Nevertheless, after a quick looking at the code, the situation doesn't seem to be hopeless. The transitioning tasks (close and release), by default (if not provided as an override), get `stagingRepositoryId` from the `registry`:
https://github.com/gradle-nexus/publish-plugin/blob/ec9b015298c54309728fa03af3b913f92aa304f5/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L101-L104

That value is set in the initialization task:
https://github.com/gradle-nexus/publish-plugin/blob/ec9b015298c54309728fa03af3b913f92aa304f5/src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt#L47

~~In the end, at the first sight, I see two places to change: set the `stagingRepositoryId` value manually, if provided by the user and conditionally remove/change dependsOn.~~

Writing the  aforementioned, I realized that conditional `dependsOn` might be more tricky as it happens at the task configuration phrase, not at the task execution (where the task parameters could be processed). It could be probably handled with the `-P`, but it might be even simpler to leave the task orchestration as is and just pass an `@Option` parameter to the initialization task, which, if provided, would override the Nexus initialization logic and just set the `stagingRepositoryId` to a provided value which would be used by the other tasks without any change.

A small caveat could be a need to call the initialization task manually, e.g.
> gw initializeXYZStagingRepository --stagingRepositoryId=12345 publishXYZToSonatype

(but probably @TWiStErRob can have a better idea how to simplify that ;) ).

Update. Rereading it before I clicked the "Comment" button, it reached me out that this mechanism would be problematic to use :-/. The `find` task was invented to do not need to manually pass the repository id. While it can be useful after the manual tests, for CI pipeline, getting the number (and passing it further) might be not very handy.

The easiest could be to just add `-PignoreInitialization` property to remove `dependsOn`, however, it might be even not needed with `-x`. The following combination should work for you:
```
gw -Pplatform=huawei initializeSonatypeStagingRepository :mylib:publishAllPublicationsToStageRepository
gw -Pplatform=google -x initializeSonatypeStagingRepository findSonatypeStagingRepository :mylib:publishAllPublicationsToStageRepository
gw findSonatypeStagingRepository closeSonatypeStagingRepository
```

The idea with `initializeXYZStagingRepository --stagingRepositoryId=12345` might also be considered to implementation, if anyone sees a sensible use case for it.

And sorry that I needed more time to get through it and you already refactored your project :-/.

**Comment by blackarrow13** [comment]
Thanks for the detailed explanation @szpak !

> The following combination should work for you:
> gw -Pplatform=huawei initializeSonatypeStagingRepository :mylib:publishAllPublicationsToStageRepository
> gw -Pplatform=google -x initializeSonatypeStagingRepository findSonatypeStagingRepository :mylib:publishAllPublicationsToStageRepository
> gw findSonatypeStagingRepository closeSonatypeStagingRepository

Good idea, I will keep that in mind if I find any problems with my current setup.
