### ISSUE TITLE
How to publish from multiple CI jobs to a single repository?

### ISSUE THREAD

**Issue by CLOVIS-AI** [gradle-nexus/publish-plugin#275]
I have a project which requires artifacts to be published from different machines (some are built on MacOS). To try this plugin, I tried to configure publishing via multiple jobs in a simpler project.

From the README, my understanding is that I should have:
- a first job that runs `initializeSonatypeStagingRepository`
- a second job that runs `findSonatypeStagingRepository publishToSonatype`
- a final job that runs `findSonatypeStagingRepository cloneSonatypeStagingRepository`

The first job [does manage to create the repository](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5161381138#L89). The second job [does manage to list it](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5161381140#L92), but [it still creates a new one](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5161381140#L108). The last job then [fails because of duplicate repositories](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5161381142#L92), which sounds normal.

Is it normal that the second job creates a new repository even though one already exists? Did I configure something incorrectly?

The full repository is [here](https://gitlab.com/opensavvy/playgrounds/gradle/-/tree/21-central-rework?ref_type=heads). The Nexus configuration is in the root `build.gradle.kts`, as requested in the documentation. The configuration of `maven-publish`, `signing` & co are in `gradle/conventions/library/src/main/kotlin/library.gradle.kts`, and is applied to the project `:core`, which I expect to be able to publish to Central.

**Comment by szpak** [comment]
Does problem in #273 cover your case? If yes, I propose to move the discussion there (where hopefully we will be able to propose some idea/solution/workaround "soon").

**Comment by CLOVIS-AI** [comment]
I'm not sure this is the same problem. In my case, I do not need different tasks or anything, all the libraries have the same type. This currently works fine, and `:closeSonatypeStagingRepository` works fine.

The only problem I have is that `:publishToSonatype` invokes `:initializeSonatypeStagingRepository`, even if `:findSonatypeStagingRepository` in the same Gradle invocation (see [here](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5161381140#L92), see lines 92 and 108).

I was expecting that, if `:findSonatypeStagingRepository` is called, `:initializeSonatypeStagingRepository` would not be called and `:publishToSonatype` would just use the found repository.

**Comment by szpak** [comment]
@CLOVIS-AI I've just looked closely at that case and put my finding in #273. If you are not interested in details, the following commands should work for you:

```
gw initializeSonatypeStagingRepository
gw -x initializeSonatypeStagingRepository findSonatypeStagingRepository publishToSonatype:mylib:publishAllPublicationsToStageRepository
gw findSonatypeStagingRepository cloneSonatypeStagingRepository
```

**Comment by szpak** [comment]
Btw, the following error from your CI:

> Too many repositories found for stagingProfileId: 2387d0230df2b4, descriptionRegex: \b\Qdev.opensavvy.playground:Playground:0.1.0+central.4\E(\s|$). If some of the repositories are not needed, consider deleting them manually. Here are the repositories matching the regular expression: [ReadStagingRepository(repositoryId=devopensavvy-1037, type=open, transitioning=false, description=dev.opensavvy.playground:Playground:0.1.0+central.4), ReadStagingRepository(repositoryId=devopensavvy-1038, type=open, transitioning=false, description=dev.opensavvy.playground:Playground:0.1.0+central.4)]

might occur even with the aforementioned commands, for example if the pipeline fails and you want to release the same version again using an another pipeline execution. One solution would be adding the pipeline ID (probably `CI_PIPELINE_IID` would enough) to `repositoryDescription` used by the tasks.

**Comment by CLOVIS-AI** [comment]
Thanks a lot, I'll try that (probably tomorrow or the day after) and report back. I'm following the other issue for curiosity's sake :)

**Comment by CLOVIS-AI** [comment]
It works <3 Thanks a lot. I was originally using `maven-publish` directly, and I kept having issues with half of the project being in a staging repository, and the other half being in another one. Of course, they wouldn't pass validation checks since the signatures were not in the same repository.

I'm really glad your plugin can fix that, I was starting to become a bit crazy
