### ISSUE TITLE
Need to ensure the plugin does not print 404 when repository is released

### ISSUE THREAD

**Issue by vlsi** [gradle-nexus/publish-plugin#29]
I've seen a case with GNSP/NPP:

```
<======-------> 50% EXECUTING [1m 17s]
GET request failed. 404: Not Found, body: [errors:[[id:*, msg:No such repository: orgapachecalcite-1089]]]
Requested operation was executed successfully in attempt 117 (maximum allowed 601)
```

It looks like GNSP/NPP was checking the state of the staging repository right after the release command. However, then Nexus responded with 404 which means "staging complete".

It would be nice to ensure the issue is not present in GNPP.
Probably the way to go is to monitor the status of the operation rather than the status of the staging repository.

**Comment by szpak** [comment]
It's GNSP, due to the way how I handle errors in the network communication layer. However, in GNPP I implemented it [differently](https://github.com/gradle-nexus/publish-plugin/blob/master/src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt#L109-L127) and the output is [nicer](https://github.com/gradle-nexus/publish-plugin/runs/703836718?check_suite_focus=true#step:5:691). Would it be ok for you?

**Comment by vlsi** [comment]
```
    Attempt 4/51 failed with result: StagingRepository(id=iogithubgradle-nexus-e2e-1313, state=closed, transitioning=true)
    Current staging repository status: state: released, transitioning: true
    Attempt 5/51 failed with result: StagingRepository(id=iogithubgradle-nexus-e2e-1313, state=released, transitioning=true)
    Current staging repository status: state: released, transitioning: true
    Attempt 6/51 failed with result: StagingRepository(id=iogithubgradle-nexus-e2e-1313, state=released, transitioning=true)
    Current staging repository status: state: released, transitioning: true
    Attempt 7/51 failed with result: StagingRepository(id=iogithubgradle-nexus-e2e-1313, state=released, transitioning=true)
    Current staging repository status: state: not_found, transitioning: false
```

1) It might be the output is too verbose. I wish there was a sane way to integrate with Gradle's progress bar (like the number of tests executed)

2) `Attempt 6/51 failed with result`. It is misleading. It is not a release attempt.
It says "failed", however, the result is not a failure.

3) `Current staging repository status: state: not_found, transitioning: false` is not that nice as well. It says something like `not_found`, which means "there's misconfiguration, and something is not found".

So I guess there's a room for improvement the output.

**Comment by szpak** [comment]
The output is with `--info`. But default (AFAIR), in a successful run, you should not see "anything" (even task names if a verbose console is not used).

I agree that "failed" could be improved somehow.

Please remember those are diagnostic messages. Therefore `not_found` is a perfectly find `state` for the staging repository.

Nevertheless, reworking timeout stuff in general there could be something done, especially with "failed".

**Comment by vlsi** [comment]
It would probably be nice if the plugin queried the repository activity and printed the new messages from the Nexus: https://github.com/gradle-nexus/publish-plugin/issues/30#issuecomment-633684017

**Comment by szpak** [comment]
Closing it in favor of https://github.com/gradle-nexus/publish-plugin/issues/30#issuecomment-633684017.
