### ISSUE TITLE
RFE: Make the description of the Nexus staging repo configurable

### ISSUE THREAD

**Issue by snazy** [gradle-nexus/publish-plugin#31]
It would be handy to be able to provide a custom description for the staging repo instead of just a string saying which plugin created it.
Additionally, can you mention the groupId+artifactId+version in the default description of the staging repo?

**Comment by marcphilipp** [comment]
> It would be handy to be able to provide a custom description for the staging repo instead of just a string saying which plugin created it.

Agreed.

> Additionally, can you mention the groupId+artifactId+version in the default description of the staging repo?

Since a staging repo can have more than one group id, artifact id, and version, it's not clear which should be used. That of the root project?

**Comment by marcphilipp** [comment]
@szpak We currently replace the description when closing/releasing the staging repo. Is passing a new description mandatory for these operations?

**Comment by szpak** [comment]
Most likely not and some default comment would be assigned by Nexus. However, I've always passed my own comment, so I'm not sure.

**Comment by snazy** [comment]
> Since a staging repo can have more than one group id, artifact id, and version, it's not clear which should be used. That of the root project?

Oh, right, you can have more than one "coordinate". Think, it doesn't really matter which artifact's used to create the description, as long it allows to distinguish different staging repos when you look into the list of staging repos in the Nexus UI. Maybe just the first artifact in a publication or so. If people really care, they can set their own description.
