### ISSUE TITLE
Migration guide from GNSP + GPP

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#34]
Wiki? Blog post? Readme entry? To explain what should be changed with the new syntax.

**Comment by szpak** [comment]
I created an initial draft of the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo). Feel free to propose enhancements or just enhance it :-).

Among others, I wonder, if we should handle there migration from custom Nexus instances? Sonatype Nexus covers majority of (non-enterprise and non-Apache cases).

**Comment by marcphilipp** [comment]
I just adjusted the wiki page to reflect the `transitionCheckOptions` change. Otherwise, it looks good to me!

Let's 🚢 it! 🙂
