### ISSUE TITLE
The current state of this plugin is enough to remove both previous plugins?

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle-nexus/publish-plugin#46]
I checked there are newer commits in the codearte plugin for example.

Is the development of this plugin paused? I would like to ask this inside discussion but it is disabled.

**Comment by marcphilipp** [comment]
Thanks for pinging us! I'm afraid @szpak were too busy with other things to finish work on this new plugin until now. However, there's not much left to be done (mostly a migration guide and timeout handling) and we still intend on finishing it. I'm hopeful I'll have some time during the holidays to work on it.
