### ISSUE TITLE
Consider registering createSimplifiedCloseAndReleaseTask task always

### ISSUE THREAD

**Issue by vlsi** [gradle-nexus/publish-plugin#51]
My use case: I want to hide the task from `./gradlew tasks` output since end-users would not use the task directly.

Currently, `createSimplifiedCloseAndReleaseTask` is registered in `afterEvaluate`, so I need my own `afterEvaluate` in order to hide the task (set `group=""`).

If the task was always registered, then it would be easier to configure/hide it.
An alternative option is to add an option to avoid "simplified closeAndRelease" task creation.

**Comment by marcphilipp** [comment]
I think we should always create it.

@szpak WDYT?

**Comment by szpak** [comment]
The tasks itself can be registered earlier. Only setting its dependencies has to be deferred a little bit.

**Comment by szpak** [comment]
Hmm, I see a test case I wrote in June:
>     internal fun `simplified close and release task without repository name should be not available if no repositories are configured`() {

What about that case? Wouldn't be confusing having that (doing nothing) task with no repositories?

**Comment by marcphilipp** [comment]
No, I think that's fine, it should just call `setDidWork(false)` in that case so it shows as "skipped".

**Comment by szpak** [comment]
@vlsi I published another SNAPSHOT for you - 1.0.0-SNAPSHOT this time.
