### ISSUE TITLE
Staging repository is not in desired state (not_found): StagingRepository(id=orgpostgresql-1612804902325, state=released, transitioning=false)

### ISSUE THREAD

**Issue by vlsi** [gradle-nexus/publish-plugin#52]
I've the following (I use https://github.com/vlsi/nexus-stub as a poorman's Nexus).

Are you sure `state=release, transitioning=false` is not valid state for Nexus as it promotes a staging repository?

AFAIK GNSP required either `not_found` or `released` state (see `(expected [released, not_found])` in https://github.com/Codearte/gradle-nexus-staging-plugin/issues/110#issue-425034006 )

`publish-plugin`:

```
    Execution failed for task ':releaseNexusStagingRepository':
        io.github.gradlenexus.publishplugin.RepositoryTransitionException: Staging repository is not in desired state (not_found): StagingRepository(id=orgpostgresql-1612804902325, state=released, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.assertRepositoryInDesiredState(StagingRepositoryTransitioner.kt:62)
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.effectivelyChangeState(StagingRepositoryTransitioner.kt:42)
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.effectivelyRelease(StagingRepositoryTransitioner.kt:35)
            at io.github.gradlenexus.publishplugin.ReleaseNexusStagingRepository.transitionStagingRepo(ReleaseNexusStagingRepository.kt:40)
            at io.github.gradlenexus.publishplugin.AbstractTransitionNexusStagingRepositoryTask.transitionStagingRepo(AbstractTransitionNexusStagingRepositoryTask.kt:66)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
```

**Comment by vlsi** [comment]
See https://github.com/Codearte/gradle-nexus-staging-plugin/issues/37 for `autoDropAfterRelease`.
However, it is not clear if `release+drop` should be atomic or not.
If `release` and `drop` are handled separately, then it might be possible to observe the repository in `state=release, transitioning=false` state.

**Comment by marcphilipp** [comment]
@szpak Could you please take a look?

**Comment by szpak** [comment]
When I was writing that code the Nexus API v2 documentation was quite poor. AFAIR, I needed to take a look in the source code of a Maven counterpart plugin to use some features (e.g. autoDrop). Most likely, I had a reason to implement it that way and your case tends to confirm that. I will tweak the implementation in GNPP.

**Comment by vlsi** [comment]
>I needed to take a look in the source code of a Maven counterpart plugin

I'm afraid Maven plugin uses "the official Nexus client" which has closed sources.

**Comment by szpak** [comment]
> I'm afraid Maven plugin uses "the official Nexus client" which has closed sources.

AFAIR, in the past, only the crucial part communicating to Nexus was closed source, not the whole plugin. Nevertheless, that didn't stop me from getting some knowledge from that project ;-).

**Comment by goncalossilva** [comment]
I'm facing a similar issue in a Kotlin Multiplatform project. It is built and released simultaneously across 3 different hosts (Linux/macOS/Windows). They all fail late in the process with a similar message, for example:

```
> Task :publishToSonatype
> Task :closeSonatypeStagingRepository

> Task :releaseSonatypeStagingRepository FAILED

FAILURE: Build failed with an exception.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

Use '--warning-mode all' to show the individual deprecation warnings.
* What went wrong:
See docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
Execution failed for task ':releaseSonatypeStagingRepository'.

> Staging repository is not in desired state [released, not_found]: StagingRepository(id=comdoist-1024, state=closed, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to gradle-nexus/publish-plugin/issues with '--info' logs
Execution optimizations have been disabled for 7 invalid unit(s) of work during this build to ensure correctness.
```

When I check Nexus, they show up as closed, and after a few seconds, they are released. The [workflow itself](https://github.com/Doist/doistx-normalize/blob/main/.github/workflows/test-publish.yml#L72) is very basic. Configuration two [[1]](https://github.com/Doist/doistx-normalize/blob/main/buildSrc/src/main/kotlin/publish.gradle.kts#L24-L97) [[2]](https://github.com/Doist/doistx-normalize/blob/main/build.gradle.kts#L91-L105).

Can there be a race condition, or is this misconfiguration on my part?

**Comment by szpak** [comment]
@goncalossilva It is not expected. I checked your logs and - as it should be - you have different staging repositories created in every build (]here](https://github.com/Doist/doistx-normalize/runs/2593142479#step:9:51) and [here](https://github.com/Doist/doistx-normalize/runs/2593142485#step:9:81)). They should be closed independently. With too short timeout they could be still "closed" , but "transitioning". However, it is not the case here:
> StagingRepository(id=comdoist-1023, state=closed, transitioning=false)

It's strange that they are effectively released after while :thinking: . Does it (being released) occur during the workflow execution or some time later?

To diagnose it I propose to:
1. Add `-i` to the Gradle execution with `./gradlew publishToSonatype ...`
2. Run the workflow.
3. Check when exactly the repositories are marked as released in Nexus UI (in comparison to the given workflow execution).
4. Remove the repositories [section](https://github.com/Doist/doistx-normalize/blob/143b53c29f9db2764baae903658b5586f8461623/buildSrc/src/main/kotlin/publish.gradle.kts#L26-L40) from the publishing block - it should be not needed (I don't know if it can break anything)
5. Run the workflow.
