### ISSUE TITLE
✨ Feature Request: GetStagingProfileTask

### ISSUE THREAD

**Issue by ryandens** [gradle-nexus/publish-plugin#60]
Is there any desired to incorporate the diagnostic `getStagingProfile` task from the `gradle-nexus-staging-plugin` to this project? I did a quick prototype and imagined it might look something like this

```kotlin
class GetStagingProfile @Inject constructor(
    objects: ObjectFactory,
    extension: NexusPublishExtension,
    repository: NexusRepository
) : AbstractNexusStagingRepositoryTask(objects, extension, repository) {

    @Optional
    @Input
    val packageGroup = objects.property<String>().apply {
        set(extension.packageGroup)
    }

    @TaskAction
    fun getStagingProfile() {
        val repository = repository.get()
        val serverUrl = repository.nexusUrl.get()
        val client = NexusClient(serverUrl, repository.username.orNull, repository.password.orNull, clientTimeout.orNull, connectTimeout.orNull)
        val stagingProfileId = client.findStagingProfileId(packageGroup = packageGroup.get()) ?: throw GradleException("Failed to find staging profile for package group: $packageGroup")
        logger.lifecycle("stagingProfileId '{}'", stagingProfileId)
    }
}
```

But I wasn't sure if this was left out unintentionally for strategic purposes - i'd be happy to contribute it with tests + update to the migration guide if this is something in line with your vision(s) for this project

As an aside, thank you for making this project! I stumbled upon it while publishing my very first artifact to maven central - this project made that a lot more approachable! ⬆️

**Comment by szpak** [comment]
Thanks @ryandens for the warm words and for your contribution proposal!

1.0.0 has been released as [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) and doesn't fully cover the features of the GNSP & GNPP duo. `getStagingProfile` can be use for diagnostic purpose and to help setup the initial configuration for faster releasing, so it could be useful to have it on board.

At the first look the implementation looks sensible. I just don't if `packageGroup` should be marked as optional. For `InitializeNexusStagingRepository` it can make sense as with `stagingProfileId` explicitly set `packageGroup` is not used. However, here we deliberately plan to ignore `stagingProfileId` even if set.

I wonder, about the format that is presented in a logger. Should it contain also the repository name (although a name of the task can be used to distinguish them)? Should it be automatic-parsing friendly in any way? Or maybe there should be also an `@Output` field set to allow others to read it (but I'm not sure why anyone would like to consume that)? @marcphilipp WDYT?

Btw, I believe, we could move NexusClient creation to a protected method in `AbstractNexusStagingRepositoryTask`, but let's postpone it to another PR.
