### ISSUE TITLE
s01.oss.sonatype.org Nexus instance

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#67]
From the Sonatype mailing list:
> On 25 February 2021, new users who sign up with Sonatype to publish to Maven Central will use https://s01.oss.sonatype.org.

More info: https://central.sonatype.org/articles/2021/Feb/23/new-users-on-s01osssonatypeorg/

We offer a way to customize an URL, however, we should mention in the documentation and maybe consider adding a predefined `sonatype01()` configuration (as `@Incubating` to see how Sonatype plans to solve it ultimately). WDYT?

**Comment by marcphilipp** [comment]
I think we should only document how to customize the URLs for now:
```kotlin
nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
        }
    }
}
```

**Comment by vlsi** [comment]
What do you think if `snapshotRepositoryUrl` defaults to something like `nexusUrl.removeSuffix("/service/local/") + , "/content/repositories/snapshots/"`?

I guess it might be nice to configure the server url just once:

```
    repositories {
        sonatype {
            nexusUrl.set(uri("https://s01.oss.sonatype.org/"))
        }
    }
```

**Comment by marcphilipp** [comment]
I totally agree that configuring the url only once would be better. For backwards compatibility, we could keep `nexusUrl` and `snapshotRepositoryUrl` and introduce a new `url` property from which we can derive the other two.

@szpak WDYT?

**Comment by szpak** [comment]
Created #73
