### ISSUE TITLE
Docs should reflect the fact that version has to be set in the root project

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle-nexus/publish-plugin#68]
I checked that I was trying to publish `-SNAPSHOT` artifacts to MavenCentral when I was trying to upload them to the snapshot repo.

The problem was I was not setting the version in the root file, so the plugin doesn't know that it is a SNAPSHOT version.

**Comment by szpak** [comment]
@JavierSegoviaCordoba Would you like to contribute a small PR with that documentation improvement?

**Comment by JavierSegoviaCordoba** [comment]
Yeah, I can

**Comment by JavierSegoviaCordoba** [comment]
Should I suggest specifying the group too?

**Comment by szpak** [comment]
Yes, please.

The default values are taken from the root project, which should not be a problem for regular builds. However, for some Android projects or monorepos they might be not set there.

**Comment by joebowbeer** [comment]
@szpak How to handle this in those Android projects where group and version are assigned differently in each subproject?

**Comment by JavierSegoviaCordoba** [comment]
@joebowbeer you want to say that you can have some subprojects in a SNAPSHOT version and others in stable?

**Comment by joebowbeer** [comment]
@JavierSegoviaCordoba In my case, only one subproject is published, but apparently I need NGPP and nexusPublishing and group and version in the root, even though publications is only in one subproject. In general, different subprojects may have different versions, including snapshot status, and even different subgroups.

**Comment by marcphilipp** [comment]
Would defining a Nexus repository for each of the subgroups and calling the appropriate publishing tasks work in that case?

**Comment by joebowbeer** [comment]
I'm not sure. nexusPublishing defines a Nexus repository? I needed to have this at the root in order for the publishToSonatype task to be created. I didn't try adding it in the subproject as well.
