### ISSUE TITLE
Separate `useStaging` from deciding which repository to publish to

### ISSUE THREAD

**Issue by tylerbenson** [gradle-nexus/publish-plugin#70]
I want to use a [nexus container](https://hub.docker.com/r/sonatype/nexus) to verify my deployment config locally, but I can't test deploying to a release repo because it expects staging capabilities. Overriding `useStaging` to false results in the snapshot repo being selected even for release versions.

**Comment by szpak** [comment]
Does it fail on a `initialize${repository.name.capitalize()}StagingRepository` task?

**Comment by marcphilipp** [comment]
@tylerbenson Sounds like you don't need this plugin but just need to specify a regular repository using the maven-publish plugin. 🤔

**Comment by tylerbenson** [comment]
I understand the sentiment... My use case is I usually publish to maven central/sonatype, but occasionally I want to verify/debug the publishing process by publishing to a local instance. This plugin gets me mostly there.  This is the main issue I ran into that prevents it from fully working.  There's an option to disable staging, why shouldn't there be an option to specify which repo?

**Comment by vlsi** [comment]
> but occasionally I want to verify/debug the publishing process by publishing to a local instance

@tylerbenson , just wondering: do you have a Nexus license for that?

I know the following solutions:
1) You can request "drop on release" profile for testing from Sonatype. You can request that like in https://issues.sonatype.org/browse/OSSRH-54596
Unfortunately, it has to use a different group id.
2) You could purchase a Nexus license (just joking :) )
3) You could use https://github.com/vlsi/nexus-stub which is a poor man's Nexus "implementation". It is not that intelligent, however, I created it exactly for the case of local dry-runs. The nice thing is it allows you to configure arbitrary group id, so you could deploy to that "server" with a mere URL change :) . Here's how I use `nexus-stub` to verify if the recent Gradle and publish-plugin can publish the files to Nexus: https://github.com/vlsi/vlsi-release-plugins/actions/workflows/release-test.yml

WDYT?

**Comment by tylerbenson** [comment]
I don't have a pro license.  I'm just using the standard nexus container, which is why I want to disable staging, but still be able to publish to snapshot/release repos.

Anyway, if you don't think separating the config out is useful I'm not going to fight for it.  Feel free to close this issue if you want.

I appreciate the plugin. Keep up the good work!

**Comment by vlsi** [comment]
Then I am puzzled. The key feature of the plugin is the staged deployment.
If you don't need staging, then you should be able to use mavenLocal (e.g. `publishToMavenLocal`). Does that work for you?

**Comment by tylerbenson** [comment]
Isn't `publishToMavenLocal` different from publishing to a "local" maven instance? IIRC, that publishes the files to the local filesystem, not uploading to a server instance.

**Comment by vlsi** [comment]
At best, gradle-nexus/publish-plugin should be able to infer target repository and the staging rules from the Nexus server itself.

In other words, it is Central's peculiarity that it forbids staging for snapshots. I guess Nexus server can be configured in such a way that it requires staging even for snapshot versions.

However, I have no idea if there's `/nexus/is_staging_required_for?group=...&version=...` API in Nexus.

It looks like the current "release version implies staging" is tied to Maven Central while the plugin name is not `gradle-central/publish-plugin` but `gradle-nexus/publish-plugin`

**Comment by tylerbenson** [comment]
Ok, thanks for writing the plugin.  It certainly helps. I'll close this issue as I don't think it's that big of deal.
