### ISSUE TITLE
How to add info into POM

### ISSUE THREAD

**Issue by Maximus905** [gradle-nexus/publish-plugin#78]
Thanks for plugin! I have a question about customizing POM file by adding info about license and developers. I try to add this info under `nexusPublishing.repositories.sonatype` like a `pom.project` but I get error:
`Could not get unknown property 'pom' for object of type io.github.gradlenexus.publishplugin.NexusRepository.`
Could you explain how can I do it correctly?

**Comment by marcphilipp** [comment]
That needs to be customized on the publication via the maven-publish plugin: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example
