### ISSUE TITLE
initializeSonatypeStagingRepository fails with status code 400

### ISSUE THREAD

**Issue by aliripe** [gradle-nexus/publish-plugin#82]
Hello,

I'm trying to integrate this plugin into our project but I'm running into issues when initializing the repository.

This is my setup:
```kotlin
nexusPublishing {
    repositories {
        create("MavenCentral") {
            username.set("valid_username")
            password.set("valid_password_for_username")
            nexusUrl.set(uri("https://oss.sonatype.org/service/local/staging/deploy/maven2/"))
            snapshotRepositoryUrl.set(uri("https://oss.sonatype.org/content/repositories/snapshots/"))
            stagingProfileId.set("valid_staging_profile_id")
        }
    }
}
```

I have a publication set up and I've already checked that the credentials and the `stagingProfileId` are correct but I keep getting:
```bash
Execution failed for task ':initializeMavenCentralStagingRepository'.
> Failed to create staging repository, server at https://oss.sonatype.org/service/local/staging/deploy/maven2/ responded with status code 400
```

It's also worth mentioning that I've already manually uploaded versions of this library to my Nexus repository, so the generated POM is correct too.

Is there anything that I'm missing?

Thank you in advance!

**Comment by marcphilipp** [comment]
@aliripe How did you determine the `stagingProfileId` that you've configured?

**Comment by aliripe** [comment]
@marcphilipp In the Nexus Repository Manager, I clicked on "Staging Profiles", then selected on the only profile that's in there and checked the URL for it, which has the format `https://oss.sonatype.org/#stagingProfiles;12345abcdef` with `12345abcdef` being the `stagingProfileId`.

Is that corrrect?

**Comment by marcphilipp** [comment]
FWIW We've added a new task (unreleased) to get the correct value in #60.

**Comment by marcphilipp** [comment]
Thanks for the update. I double-checked the default URLs:
https://github.com/gradle-nexus/publish-plugin/blob/f3c24a7b92c5b282fa921cb5f8c966aff6dbf306/src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt#L36-L37

Thus, looks like your `nexusUrl` was slightly off.
