### ISSUE TITLE
Log explicit response body in case of HTTP errors

### ISSUE THREAD

**Issue by hiddewie** [gradle-nexus/publish-plugin#91]
Thanks for the great plugin!

I was running into a configuration error, and the (Gradle) exception message was the following
```
> Failed to load staging profiles, server at https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ responded with status code 400, body: io.github.gradlenexus.publishplugin.shadow.okhttp3.ResponseBody$1@527c85e2
```

It would be very nice to see the full response body, because that usually tells more about the problem than a plain object reference.

**Comment by szpak** [comment]
It is somehow tricky with [HTTP responses](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/) - can be consumed just once. Nevertheless, we don't expect very large responses in our calls (to risk OutOfMemory) and probably in the majority of cases (POSTs) we don't rely on the value, so it should be possible to improve.

Btw, @hiddewie Would you like to give it a shot? ;-)

**Comment by hiddewie** [comment]
Definitely!

The error response can be read in total I think, because it will never be used later, because a RuntimeException is thrown directly after reading the body.

**Comment by hiddewie** [comment]
See linked PR https://github.com/gradle-nexus/publish-plugin/pull/92
